version: '3.8'

services:
  postgres:
    image: postgres:16.1-alpine3.19
    environment:
      - POSTGRES_DB=dbo
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"